# GitHub Pages configuration
title: "Pizza Divider Documentation"
description: "Technical documentation for the Pizza Divider application"
baseurl: "/pizza-divider"
url: "https://jun-t-git.github.io"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/