# GitHub Pages configuration for Jekyll
title: "Pizza Divider Documentation"
description: "Technical documentation for the Pizza Divider application"
baseurl: ""
url: "https://jun-t-git.github.io/pizza-divider"

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-github-metadata

# Enable Mermaid diagrams
kramdown:
  input: GFM
  syntax_highlighter: rouge