source "https://rubygems.org"

# GitHub Pages gem - これが重要！
gem "github-pages", "~> 228", group: :jekyll_plugins

# Additional gems
gem "webrick", "~> 1.8"

# Windows and JRuby support
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]