source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "kramdown-parser-gfm"
gem "rouge"
gem "webrick" # Required for Ruby 3.0+

group :jekyll_plugins do
  gem "jekyll-github-metadata"
  gem "jekyll-relative-links"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]